### ISSUE TITLE
70-90?

### ISSUE THREAD

**Issue by CottonCollecter** [ekknod/xilinx_cfg#1]
Hello ekknod, thanks for your great work.  I can modify other block except 70-90 on pcie_7x_0_core_top.v i still not figure out how to modify 70-90, it always show 00 on cfgspace. Does these block need modify other .v file? Or something i didn't noticed?

**Comment by ekknod** [comment]
https://japan.xilinx.com/content/dam/xilinx/support/documents/ip_documentation/pcie_7x/v3_3/pg054-7series-pcie.pdf

-

Keep in mind. some of these configuration space values are set by the device driver [RW].

**Comment by CottonCollecter** [comment]
So could i get a conclusion that all cfgspace can modify in pcie_7x_0_core_top.v？
