### ISSUE TITLE
Why the output values ​​are the same

### ISSUE THREAD

**Issue by kaili7690** [ekknod/xilinx_cfg#3]
great ekknod 
Why is the output still the same after I change the parameters of leet_cfg[], and the same is true when compiling and running under the default data?
![QQ截图20240712013255](https://github.com/ekknod/xilinx_cfg/assets/60280469/77be8fab-b8df-4e0f-9632-e7b568681f7e)
![QQ截图20240712013303](https://github.com/ekknod/xilinx_cfg/assets/60280469/0bbfa7a1-86ad-473a-bcfa-4b60942927b4)

**Comment by ByBJIuk** [comment]
Did you figure out how to get your data? I insert my cfg but I can't get my data either
